/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code.cursoem.video;

/**
 *
 * @author Alisson Alves
 */
public class ContadorWhile extends javax.swing.JFrame {

    /**
     * Creates new form ContadorWhile
     */
    public ContadorWhile() {
        initComponents();
        LbNumeroLimite.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbImageFatorial = new javax.swing.JLabel();
        LbTextoFatorial = new javax.swing.JLabel();
        SpnValorFatorial = new javax.swing.JSpinner();
        LbResultadoFatorial = new javax.swing.JLabel();
        LbDesenvolvedor = new javax.swing.JLabel();
        LbTitlePrincipal = new javax.swing.JLabel();
        LbNumeroLimite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbImageFatorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/cursoem/video/fatorialnovo.png"))); // NOI18N

        LbTextoFatorial.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LbTextoFatorial.setText("F! =");

        SpnValorFatorial.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        SpnValorFatorial.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        SpnValorFatorial.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpnValorFatorialStateChanged(evt);
            }
        });

        LbResultadoFatorial.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LbResultadoFatorial.setForeground(new java.awt.Color(255, 0, 51));
        LbResultadoFatorial.setText("1");

        LbDesenvolvedor.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        LbDesenvolvedor.setText("Desenvolvido por: Álisson Alves");

        LbTitlePrincipal.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        LbTitlePrincipal.setText("Fatorial Calc  - v1.0");

        LbNumeroLimite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbNumeroLimite.setForeground(new java.awt.Color(255, 0, 51));
        LbNumeroLimite.setText("Número limite atingido!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbDesenvolvedor)
                            .addComponent(LbTitlePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SpnValorFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbTextoFatorial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbResultadoFatorial)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(LbNumeroLimite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbImageFatorial)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbTitlePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpnValorFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbTextoFatorial)
                            .addComponent(LbResultadoFatorial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbNumeroLimite)
                        .addGap(18, 18, 18)
                        .addComponent(LbDesenvolvedor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbImageFatorial)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpnValorFatorialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpnValorFatorialStateChanged
        int n = Integer.parseInt(SpnValorFatorial.getValue().toString());
        int fatorial = 1;
        int i = n;
        // 5! = 5 x 4 x 3 x 2 x 1
        if (n == 12){
            LbNumeroLimite.setVisible(true);
        }else{
            LbNumeroLimite.setVisible(false);
        }
        while(i >= 1){
            fatorial = fatorial * i;
            i--;
        }
        LbResultadoFatorial.setText(Integer.toString(fatorial));
    }//GEN-LAST:event_SpnValorFatorialStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorWhile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorWhile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorWhile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorWhile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorWhile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbDesenvolvedor;
    private javax.swing.JLabel LbImageFatorial;
    private javax.swing.JLabel LbNumeroLimite;
    private javax.swing.JLabel LbResultadoFatorial;
    private javax.swing.JLabel LbTextoFatorial;
    private javax.swing.JLabel LbTitlePrincipal;
    private javax.swing.JSpinner SpnValorFatorial;
    // End of variables declaration//GEN-END:variables
}
