/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code.cursoem.video;

/**
 *
 * @author Alisson Alves
 */
public class TiposDeTriangulos extends javax.swing.JFrame {

    /**
     * Creates new form TiposDeTriangulos
     */
    public TiposDeTriangulos() {
        initComponents();
        setLocationRelativeTo(null);
        PanResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbSegmentoA = new javax.swing.JLabel();
        LbSegmentoB = new javax.swing.JLabel();
        LbSegmentoC = new javax.swing.JLabel();
        SldA = new javax.swing.JSlider();
        SldB = new javax.swing.JSlider();
        SldC = new javax.swing.JSlider();
        LbValorSegC = new javax.swing.JLabel();
        LbValorSegA = new javax.swing.JLabel();
        LbValorSegB = new javax.swing.JLabel();
        BtVerificar = new javax.swing.JButton();
        PanResultado = new javax.swing.JPanel();
        LbFormaTriangulo = new javax.swing.JLabel();
        LbTipoTriangulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LbDesenvolvedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbSegmentoA.setText("SEGMENTO A");

        LbSegmentoB.setText("SEGMENTO B");

        LbSegmentoC.setText("SEGMENTO C");

        SldA.setMaximum(20);
        SldA.setValue(0);
        SldA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SldAStateChanged(evt);
            }
        });

        SldB.setMaximum(20);
        SldB.setValue(0);
        SldB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SldBStateChanged(evt);
            }
        });

        SldC.setMaximum(20);
        SldC.setValue(0);
        SldC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SldCStateChanged(evt);
            }
        });

        LbValorSegC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbValorSegC.setText("0");

        LbValorSegA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbValorSegA.setText("0");

        LbValorSegB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbValorSegB.setText("0");

        BtVerificar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtVerificar.setText("VERIFICAR");
        BtVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVerificarActionPerformed(evt);
            }
        });

        PanResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbFormaTriangulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LbFormaTriangulo.setForeground(new java.awt.Color(51, 51, 255));
        LbFormaTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbFormaTriangulo.setText("Forma ou Não?");

        LbTipoTriangulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LbTipoTriangulo.setForeground(new java.awt.Color(51, 255, 0));
        LbTipoTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTipoTriangulo.setText("Tipo de Triângulo");

        javax.swing.GroupLayout PanResultadoLayout = new javax.swing.GroupLayout(PanResultado);
        PanResultado.setLayout(PanResultadoLayout);
        PanResultadoLayout.setHorizontalGroup(
            PanResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbFormaTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbTipoTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanResultadoLayout.setVerticalGroup(
            PanResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbFormaTriangulo)
                .addGap(30, 30, 30)
                .addComponent(LbTipoTriangulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/cursoem/video/triangulo 1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jogo dos Triângulos!");

        LbDesenvolvedor.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        LbDesenvolvedor.setText("Desenvolvido por: Álisson Alves");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbSegmentoA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbValorSegA))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbSegmentoC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbValorSegC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbSegmentoB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbValorSegB))
                            .addComponent(BtVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbDesenvolvedor)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbSegmentoA)
                            .addComponent(SldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbValorSegA))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbSegmentoB)
                            .addComponent(SldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbValorSegB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbValorSegC)
                            .addComponent(LbSegmentoC)
                            .addComponent(SldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BtVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(PanResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbDesenvolvedor)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVerificarActionPerformed
        int a, b, c;
        PanResultado.setVisible(true);
        
        a = SldA.getValue();
        b = SldB.getValue();
        c = SldC.getValue();
        
        if (a < (b + c) && b < (a + c) && c < (a + b)){
            LbFormaTriangulo.setText("Formam um triângulo!");
            if (a == b && b == c){
                LbTipoTriangulo.setText("Equilátero");
            }else if(a != b && b != c && c != a){
                LbTipoTriangulo.setText("Escaleno");
            }else{
                LbTipoTriangulo.setText("Isósceles!");
            }
        }else{
            LbFormaTriangulo.setText("Não Formam um triângulo!");
            LbTipoTriangulo.setText("NaN");
        }
    }//GEN-LAST:event_BtVerificarActionPerformed

    private void SldAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SldAStateChanged
        LbValorSegA.setText(Integer.toString(SldA.getValue()));
    }//GEN-LAST:event_SldAStateChanged

    private void SldBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SldBStateChanged
        LbValorSegB.setText(Integer.toString(SldB.getValue()));
    }//GEN-LAST:event_SldBStateChanged

    private void SldCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SldCStateChanged
        LbValorSegC.setText(Integer.toString(SldC.getValue()));
    }//GEN-LAST:event_SldCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiposDeTriangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiposDeTriangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiposDeTriangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiposDeTriangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiposDeTriangulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtVerificar;
    private javax.swing.JLabel LbDesenvolvedor;
    private javax.swing.JLabel LbFormaTriangulo;
    private javax.swing.JLabel LbSegmentoA;
    private javax.swing.JLabel LbSegmentoB;
    private javax.swing.JLabel LbSegmentoC;
    private javax.swing.JLabel LbTipoTriangulo;
    private javax.swing.JLabel LbValorSegA;
    private javax.swing.JLabel LbValorSegB;
    private javax.swing.JLabel LbValorSegC;
    private javax.swing.JPanel PanResultado;
    private javax.swing.JSlider SldA;
    private javax.swing.JSlider SldB;
    private javax.swing.JSlider SldC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
