/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code.cursoem.video;

/**
 *
 * @author Alisson Alves
 */
public class CalcSoma extends javax.swing.JFrame {

    /**
     * Creates new form CalcSoma
     */
    public CalcSoma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbImage = new javax.swing.JLabel();
        LbTitle = new javax.swing.JLabel();
        TxtSomaN1 = new javax.swing.JTextField();
        TxtSomaN2 = new javax.swing.JTextField();
        BtCalculaSoma = new javax.swing.JButton();
        LbSomaOp = new javax.swing.JLabel();
        LbResultadoSoma = new javax.swing.JLabel();
        TxtSubN1 = new javax.swing.JTextField();
        TxtSubN2 = new javax.swing.JTextField();
        BtCalculaSub = new javax.swing.JButton();
        LbSomaOp1 = new javax.swing.JLabel();
        LbResultadoSub = new javax.swing.JLabel();
        TxtMultN2 = new javax.swing.JTextField();
        BtCalculaMult = new javax.swing.JButton();
        LbMultOp = new javax.swing.JLabel();
        LbResultadoMult = new javax.swing.JLabel();
        TxtMultN1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/cursoem/video/calc.png"))); // NOI18N

        LbTitle.setFont(new java.awt.Font("Gabriola", 3, 48)); // NOI18N
        LbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTitle.setText("CALC FÁCIL");
        LbTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TxtSomaN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSomaN1ActionPerformed(evt);
            }
        });

        TxtSomaN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSomaN2ActionPerformed(evt);
            }
        });

        BtCalculaSoma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtCalculaSoma.setText("=");
        BtCalculaSoma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtCalculaSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalculaSomaActionPerformed(evt);
            }
        });

        LbSomaOp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LbSomaOp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSomaOp.setText("+");

        LbResultadoSoma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbResultadoSoma.setText("0");

        TxtSubN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubN1ActionPerformed(evt);
            }
        });

        TxtSubN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubN2ActionPerformed(evt);
            }
        });

        BtCalculaSub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtCalculaSub.setText("=");
        BtCalculaSub.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtCalculaSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalculaSubActionPerformed(evt);
            }
        });

        LbSomaOp1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbSomaOp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSomaOp1.setText("-");

        LbResultadoSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbResultadoSub.setText("0");

        TxtMultN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMultN2ActionPerformed(evt);
            }
        });

        BtCalculaMult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtCalculaMult.setText("=");
        BtCalculaMult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtCalculaMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalculaMultActionPerformed(evt);
            }
        });

        LbMultOp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LbMultOp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMultOp.setText("X");

        LbResultadoMult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbResultadoMult.setText("0");

        TxtMultN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMultN1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel1.setText("Desenvolvido por: Álisson Alves");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtSubN1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LbSomaOp1)
                                        .addGap(6, 6, 6)
                                        .addComponent(TxtSubN2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtCalculaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LbResultadoSub))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtSomaN1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LbSomaOp)
                                        .addGap(6, 6, 6)
                                        .addComponent(TxtSomaN2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtCalculaSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LbResultadoSoma))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtMultN1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LbMultOp)
                                        .addGap(6, 6, 6)
                                        .addComponent(TxtMultN2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtCalculaMult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LbResultadoMult))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(LbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbSomaOp)
                            .addComponent(TxtSomaN2)
                            .addComponent(TxtSomaN1)
                            .addComponent(BtCalculaSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbResultadoSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbSomaOp1)
                            .addComponent(TxtSubN2)
                            .addComponent(TxtSubN1)
                            .addComponent(BtCalculaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbResultadoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbMultOp)
                            .addComponent(TxtMultN2)
                            .addComponent(TxtMultN1)
                            .addComponent(BtCalculaMult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbResultadoMult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtSomaN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSomaN1ActionPerformed

    }//GEN-LAST:event_TxtSomaN1ActionPerformed

    private void TxtSomaN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSomaN2ActionPerformed
       
    }//GEN-LAST:event_TxtSomaN2ActionPerformed

    private void BtCalculaSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalculaSomaActionPerformed
        float n1Soma = Float.parseFloat(TxtSomaN1.getText());
        float n2Soma = Float.parseFloat(TxtSomaN2.getText());
        float soma = n1Soma + n2Soma;
        LbResultadoSoma.setText(Float.toString(soma));
    }//GEN-LAST:event_BtCalculaSomaActionPerformed

    private void TxtSubN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubN1ActionPerformed

    private void TxtSubN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubN2ActionPerformed

    private void BtCalculaSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalculaSubActionPerformed
        float n1Sub = Float.parseFloat(TxtSubN1.getText());
        float n2Sub = Float.parseFloat(TxtSubN2.getText());
        float subtracao = n1Sub - n2Sub;
        LbResultadoSub.setText(Float.toString(subtracao));
    }//GEN-LAST:event_BtCalculaSubActionPerformed

    private void TxtMultN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMultN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMultN2ActionPerformed

    private void BtCalculaMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalculaMultActionPerformed
        float n1Mult = Float.parseFloat(TxtMultN1.getText());
        float n2Mult = Float.parseFloat(TxtMultN2.getText());
        float Mult = n1Mult * n2Mult;
        LbResultadoMult.setText(Float.toString(Mult));
    }//GEN-LAST:event_BtCalculaMultActionPerformed

    private void TxtMultN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMultN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMultN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcSoma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCalculaMult;
    private javax.swing.JButton BtCalculaSoma;
    private javax.swing.JButton BtCalculaSub;
    private javax.swing.JLabel LbImage;
    private javax.swing.JLabel LbMultOp;
    private javax.swing.JLabel LbResultadoMult;
    private javax.swing.JLabel LbResultadoSoma;
    private javax.swing.JLabel LbResultadoSub;
    private javax.swing.JLabel LbSomaOp;
    private javax.swing.JLabel LbSomaOp1;
    private javax.swing.JLabel LbTitle;
    private javax.swing.JTextField TxtMultN1;
    private javax.swing.JTextField TxtMultN2;
    private javax.swing.JTextField TxtSomaN1;
    private javax.swing.JTextField TxtSomaN2;
    private javax.swing.JTextField TxtSubN1;
    private javax.swing.JTextField TxtSubN2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
