/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code.cursoem.video;

import java.util.Calendar;

/**
 *
 * @author Alisson Alves
 */
public class TelaIdade extends javax.swing.JFrame {

    /**
     * Creates new form TelaIdade
     */
    public TelaIdade() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbImage = new javax.swing.JLabel();
        LbTitle = new javax.swing.JLabel();
        LbAnoNascimento = new javax.swing.JLabel();
        SpnAnoNascimento = new javax.swing.JSpinner();
        BtCalculaIdade = new javax.swing.JButton();
        LbMostraIdade = new javax.swing.JLabel();
        LbSituacaoVoto = new javax.swing.JLabel();
        LbMostraSituacaoVoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        LbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/cursoem/video/pessoas.png"))); // NOI18N

        LbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LbTitle.setText("ELEIÇÕES 2022");

        LbAnoNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbAnoNascimento.setText("Ano de Nascimento");

        BtCalculaIdade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtCalculaIdade.setText("Calcular Idade");
        BtCalculaIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalculaIdadeActionPerformed(evt);
            }
        });

        LbMostraIdade.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LbMostraIdade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbMostraIdade.setText("Idade.");

        LbSituacaoVoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbSituacaoVoto.setText("Situação de Voto ->");

        LbMostraSituacaoVoto.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LbMostraSituacaoVoto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbMostraSituacaoVoto.setText("Resultado.");

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel1.setText("Desenvolvido por: Álisson Alves");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpnAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbSituacaoVoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtCalculaIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LbMostraIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LbMostraSituacaoVoto, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbAnoNascimento)
                            .addComponent(SpnAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtCalculaIdade)
                            .addComponent(LbMostraIdade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbSituacaoVoto)
                            .addComponent(LbMostraSituacaoVoto))))
                .addGap(18, 18, 18)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCalculaIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalculaIdadeActionPerformed
        int anoNascimento = Integer.parseInt(SpnAnoNascimento.getValue().toString());
        Calendar anoAtualSistema = Calendar.getInstance();
        int anoAtual = anoAtualSistema.get(Calendar.YEAR);
        int idade = anoAtual-anoNascimento;
        LbMostraIdade.setText(Integer.toString(idade)+" Anos.");
        
        String situacao = (idade >= 16 && idade < 18)?"OPCIONAL!":"OBRIGATÓRIO!";
        LbMostraSituacaoVoto.setText(situacao);
    }//GEN-LAST:event_BtCalculaIdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIdade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCalculaIdade;
    private javax.swing.JLabel LbAnoNascimento;
    private javax.swing.JLabel LbImage;
    private javax.swing.JLabel LbMostraIdade;
    private javax.swing.JLabel LbMostraSituacaoVoto;
    private javax.swing.JLabel LbSituacaoVoto;
    private javax.swing.JLabel LbTitle;
    private javax.swing.JSpinner SpnAnoNascimento;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
