/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code.cursoem.video;

import javax.swing.DefaultListModel;

/**
 *
 * @author Alisson Alves
 */
public class ContadorFor extends javax.swing.JFrame {

    /**
     * Creates new form ContadorFor
     */
    public ContadorFor() {
        initComponents();
        setLocationRelativeTo(null);
        SldPasso.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTextoInicio = new javax.swing.JLabel();
        LbTextoFim = new javax.swing.JLabel();
        LbTextoPasso = new javax.swing.JLabel();
        SldInicio = new javax.swing.JSlider();
        SldFim = new javax.swing.JSlider();
        SldPasso = new javax.swing.JSlider();
        LbValorInicio = new javax.swing.JLabel();
        LbValorFim = new javax.swing.JLabel();
        LbValorPasso = new javax.swing.JLabel();
        btnCont = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LstMostraLista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        LbTitlePrincipal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LbDesenvolvedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LbTextoInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbTextoInicio.setText("Início");

        LbTextoFim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbTextoFim.setText("Fim");

        LbTextoPasso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbTextoPasso.setText("Passo");

        SldInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SldInicio.setMaximum(5);
        SldInicio.setValue(0);
        SldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SldInicioStateChanged(evt);
            }
        });

        SldFim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SldFim.setMaximum(20);
        SldFim.setMinimum(6);
        SldFim.setValue(6);
        SldFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SldFimStateChanged(evt);
            }
        });

        SldPasso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SldPasso.setMaximum(4);
        SldPasso.setMinimum(1);
        SldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SldPassoStateChanged(evt);
            }
        });

        LbValorInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbValorInicio.setText("0");

        LbValorFim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbValorFim.setText("6");

        LbValorPasso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbValorPasso.setText("1");

        btnCont.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCont.setForeground(new java.awt.Color(255, 51, 51));
        btnCont.setText("FAZER CONTAGEM");
        btnCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContActionPerformed(evt);
            }
        });

        LstMostraLista.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(LstMostraLista);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/cursoem/video/contador.jpg"))); // NOI18N

        LbTitlePrincipal.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        LbTitlePrincipal.setText("CONTADOR VIRTUAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Configure sua contagem abaixo: ");

        LbDesenvolvedor.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        LbDesenvolvedor.setText("Desenvolvido por: Álisson Alves");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbTitlePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbTextoFim)
                                    .addComponent(LbTextoInicio)
                                    .addComponent(LbTextoPasso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(LbValorPasso))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(SldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LbValorFim))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(SldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(LbValorInicio))))
                            .addComponent(btnCont, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(LbDesenvolvedor)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(LbTitlePrincipal)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbValorInicio)
                            .addComponent(SldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbTextoInicio))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbValorFim)
                            .addComponent(SldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbTextoFim))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbValorPasso)
                            .addComponent(SldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbTextoPasso))
                        .addGap(18, 18, 18)
                        .addComponent(btnCont))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbDesenvolvedor)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SldInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SldInicioStateChanged
        int i = SldInicio.getValue();
        LbValorInicio.setText(Integer.toString(i));
    }//GEN-LAST:event_SldInicioStateChanged

    private void SldFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SldFimStateChanged
        int fim = SldFim.getValue();
        LbValorFim.setText(Integer.toString(fim));
    }//GEN-LAST:event_SldFimStateChanged

    private void SldPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SldPassoStateChanged
       
        int passo = SldPasso.getValue();
        LbValorPasso.setText(Integer.toString(passo));
    }//GEN-LAST:event_SldPassoStateChanged

    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContActionPerformed
        int i, fim, passo;
        
        i = SldInicio.getValue();
        fim = SldFim.getValue();
        passo = SldPasso.getValue();
        
        DefaultListModel lista = new DefaultListModel();
        for (int contador = i; contador <= fim; contador += passo){
            lista.addElement(contador);
        }
        LstMostraLista.setModel(lista);
    }//GEN-LAST:event_btnContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorFor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorFor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbDesenvolvedor;
    private javax.swing.JLabel LbTextoFim;
    private javax.swing.JLabel LbTextoInicio;
    private javax.swing.JLabel LbTextoPasso;
    private javax.swing.JLabel LbTitlePrincipal;
    private javax.swing.JLabel LbValorFim;
    private javax.swing.JLabel LbValorInicio;
    private javax.swing.JLabel LbValorPasso;
    private javax.swing.JList<String> LstMostraLista;
    private javax.swing.JSlider SldFim;
    private javax.swing.JSlider SldInicio;
    private javax.swing.JSlider SldPasso;
    private javax.swing.JButton btnCont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
