/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code.cursoem.video;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author Alisson Alves
 */
public class VetoresSwing extends javax.swing.JFrame {
    
    // Declaração do vetor e do objeto ListModel
    int vetor[] = new int [5];
    DefaultListModel lista = new DefaultListModel();
    
    /*Esse atributo servirá para indicar qual o elemento do vetor 
    estar selecionado em tempo de execução. Iniciando em 0 já que o vetor está vazio*/
    int ElementoSelecionado = 0;
    
    public VetoresSwing() {
        initComponents();
        
        //iniciar o programa no centro da tela
        setLocationRelativeTo(null);
        
        //Imprimir o vetor zerado assim que inicia o programa
        for (int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpnValorInserir = new javax.swing.JSpinner();
        BtAdicionar = new javax.swing.JButton();
        BtRemover = new javax.swing.JButton();
        BtOrdenar = new javax.swing.JButton();
        TextoVetor = new javax.swing.JLabel();
        LbPosicaoSelecionada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListVetor = new javax.swing.JList<>();
        LbDesenvolvedor = new javax.swing.JLabel();
        LbTitlePrincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SpnValorInserir.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        BtAdicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtAdicionar.setText("Adicionar");
        BtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAdicionarActionPerformed(evt);
            }
        });

        BtRemover.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtRemover.setText("Remover");
        BtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverActionPerformed(evt);
            }
        });

        BtOrdenar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtOrdenar.setText("Ordenar");
        BtOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtOrdenarActionPerformed(evt);
            }
        });

        TextoVetor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextoVetor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextoVetor.setText("VETOR ->");

        LbPosicaoSelecionada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbPosicaoSelecionada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbPosicaoSelecionada.setText("[ 0 ]");

        ListVetor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListVetor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ListVetor.setModel(lista);
        ListVetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListVetorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListVetor);

        LbDesenvolvedor.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        LbDesenvolvedor.setText("Desenvolvido por: Álisson Alves");

        LbTitlePrincipal.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        LbTitlePrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTitlePrincipal.setText("VETORES DINÂMICOS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Monte seu vetor personalizado! :D");

        jLabel2.setText("---------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbTitlePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(LbDesenvolvedor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SpnValorInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextoVetor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LbPosicaoSelecionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTitlePrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbPosicaoSelecionada)
                            .addComponent(TextoVetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SpnValorInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtAdicionar)
                        .addGap(20, 20, 20)
                        .addComponent(BtRemover)
                        .addGap(20, 20, 20)
                        .addComponent(BtOrdenar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(LbDesenvolvedor)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAdicionarActionPerformed
        //O primeiro elemento do vetor será incluído na posição 0
        vetor[ElementoSelecionado] = Integer.parseInt(SpnValorInserir.getValue().toString());
        
        //Limpando a lista para poder mostrá-la mostrá-la 
        lista.removeAllElements();
        for (int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
        //Apagando o valor do spinner após a inclusão
        SpnValorInserir.setValue(0);
    }//GEN-LAST:event_BtAdicionarActionPerformed

    private void ListVetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListVetorMouseClicked
        // Atribuindo o valor do elemento selecionado pelo mouse a variável ElementoSelecionado que antes valia 0
        ElementoSelecionado = ListVetor.getSelectedIndex();
        //Mostrando no label acima da lista o índice do elemento selecionado no vetor
        LbPosicaoSelecionada.setText("[ " + ElementoSelecionado + " ]");
    }//GEN-LAST:event_ListVetorMouseClicked

    private void BtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverActionPerformed
        //Ao clicar no botão remover o elemento selecionado será substituído por 0
        vetor[ElementoSelecionado] = 0;
        lista.removeAllElements();
        for (int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }//GEN-LAST:event_BtRemoverActionPerformed

    private void BtOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtOrdenarActionPerformed
        //Usando o método sort para ordenar todo o vetor
        Arrays.sort(vetor);
        lista.removeAllElements();
        for (int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }//GEN-LAST:event_BtOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetoresSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdicionar;
    private javax.swing.JButton BtOrdenar;
    private javax.swing.JButton BtRemover;
    private javax.swing.JLabel LbDesenvolvedor;
    private javax.swing.JLabel LbPosicaoSelecionada;
    private javax.swing.JLabel LbTitlePrincipal;
    private javax.swing.JList<String> ListVetor;
    private javax.swing.JSpinner SpnValorInserir;
    private javax.swing.JLabel TextoVetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
