/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code.cursoem.video;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author Alisson Alves
 */
public class VetoresSwing extends javax.swing.JFrame {
    
    int vetor[] = new int [5];
    DefaultListModel lista = new DefaultListModel();
    int selecionado = 0;
    
    public VetoresSwing() {
        initComponents();
        setLocationRelativeTo(null);
        for (int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpnValorInserir = new javax.swing.JSpinner();
        BtAdicionar = new javax.swing.JButton();
        BtRemover = new javax.swing.JButton();
        BtOrdenar = new javax.swing.JButton();
        TextoVetor = new javax.swing.JLabel();
        LbPosicaoSelecionada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListVetor = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SpnValorInserir.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        BtAdicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtAdicionar.setText("Adicionar");
        BtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAdicionarActionPerformed(evt);
            }
        });

        BtRemover.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtRemover.setText("Remover");
        BtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverActionPerformed(evt);
            }
        });

        BtOrdenar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtOrdenar.setText("Ordenar");
        BtOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtOrdenarActionPerformed(evt);
            }
        });

        TextoVetor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextoVetor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextoVetor.setText("VETOR ->");

        LbPosicaoSelecionada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbPosicaoSelecionada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbPosicaoSelecionada.setText("[ 0 ]");

        ListVetor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListVetor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ListVetor.setModel(lista);
        ListVetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListVetorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListVetor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TextoVetor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbPosicaoSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpnValorInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPosicaoSelecionada)
                    .addComponent(TextoVetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SpnValorInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtAdicionar)
                        .addGap(20, 20, 20)
                        .addComponent(BtRemover)
                        .addGap(20, 20, 20)
                        .addComponent(BtOrdenar))
                    .addComponent(jScrollPane1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAdicionarActionPerformed
        vetor[selecionado] = Integer.parseInt(SpnValorInserir.getValue().toString());
        lista.removeAllElements();
        for (int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }//GEN-LAST:event_BtAdicionarActionPerformed

    private void ListVetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListVetorMouseClicked
        selecionado = ListVetor.getSelectedIndex();
        LbPosicaoSelecionada.setText("[ " + selecionado + " ]");
    }//GEN-LAST:event_ListVetorMouseClicked

    private void BtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverActionPerformed
        vetor[selecionado] = 0;
        lista.removeAllElements();
        for (int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }//GEN-LAST:event_BtRemoverActionPerformed

    private void BtOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtOrdenarActionPerformed
        Arrays.sort(vetor);
        lista.removeAllElements();
        for (int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }//GEN-LAST:event_BtOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetoresSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdicionar;
    private javax.swing.JButton BtOrdenar;
    private javax.swing.JButton BtRemover;
    private javax.swing.JLabel LbPosicaoSelecionada;
    private javax.swing.JList<String> ListVetor;
    private javax.swing.JSpinner SpnValorInserir;
    private javax.swing.JLabel TextoVetor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
